version: 2
updates:
  # Maintain GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  # Maintain Poetry Dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"

  # Maintain Docker Dependencies
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
